version: 1
project:
  name: color-separator
analyze:
  modules:
    - name: frontend
      type: npm
      target: .
      path: .
    - name: backend
      type: pip
      target: backend/requirements.txt
      path: backend
exclude:
  - backend/venv
  - backend/weights
  - backend/sam2.1_t.pt
  - backend/__pycache__
