export const ARTICLE_TITLE = "What's a \"Public Internet?\"";
export const ARTICLE_SUBTITLE = "You don't want Nigel Farage moderating your social media, right?";
export const ARTICLE_AUTHOR = "Cory Doctorow";
export const ARTICLE_SOURCE = "Pluralistic";
export const ARTICLE_DATE = "Jun 25, 2025";

export const ARTICLE_PARAGRAPHS: string[] = [
  `The Eurostack represents a long-overdue European initiative to develop independent technology infrastructure separate from American Big Tech corporations, as well as technology from other major powers. Europe has spent decades as a vassal state in the digital realm, hosting its citizens' most intimate data on American servers, subject to American law, accessible to American spy agencies, and managed by American corporations whose interests rarely align with those of European citizens. The Eurostack is an attempt to change all that.`,

  `But "technological sovereignty" is a concept that can serve liberation or oppression, depending on its implementation. Data localization policies — requiring that citizen data remain on domestic servers — can protect against NSA surveillance, but they can also enable authoritarian regimes to access population data for repression. The Chinese government's insistence on data localization isn't about protecting Chinese people from American spying; it's about ensuring the Chinese state can spy on its own citizens without impediment. The concept risks fragmenting the internet into isolated national networks controlled by thuggish customs inspectors who determine what crosses their digital borders.`,

  `At its best, technological sovereignty creates a genuinely public internet — one where individuals exercise meaningful control over their own digital participation, determining who sees their communications and whom they can access, while maintaining interoperability across borders. At its worst, it creates a series of national firewalls, each controlled by whatever demagogue happens to be in power at the moment.`,

  `A public internet requires government involvement — funding, regulation, and oversight — though this differs fundamentally from government operation of all services. The distinction matters enormously, and it's one that both the left and the right consistently fail to grasp. The left tends to assume that government provision is inherently virtuous; the right tends to assume it's inherently corrupt. Both are wrong, and the truth is far more interesting and consequential.`,

  `Consider fiber optic infrastructure. Fiber is the optimal internet delivery method, capable of transmitting billions of times more data than copper wires. A single fiber strand can carry more data than all the copper telephone wires ever manufactured. The cost of fiber is almost entirely in the installation — the digging, the rights-of-way, the permits, the restoration of surfaces — not in the glass itself. Once you've laid fiber, upgrading its capacity is mostly a matter of swapping out the equipment at either end.`,

  `But private companies cannot economically secure the property rights and rights-of-way necessary for comprehensive fiber deployment on their own. You need to dig up roads, cross railway lines, tunnel under rivers, string cables between poles on public land. Every meter of fiber requires some form of government involvement — permits at minimum, often outright government construction of the pathway.`,

  `Government intervention is essential, but it can take radically different forms, and the form it takes determines whether you end up with liberation or oppression. The worst model involves the government clearing rights-of-way and granting a single private company the exclusive right to use them. This creates a private monopoly backstopped by public power — the worst of both worlds.`,

  `Such monopolies can deny service to unprofitable areas, charge exorbitant connection fees, skimp on maintenance, impose junk charges, favor corporate clients over residential ones, violate net neutrality principles, and censor content. Since private corporations are not bound by the First Amendment, a private monopoly ISP can silence any speech it dislikes — or any speech that a government official informally requests it to silence — without any constitutional constraint.`,

  `Regulation can improve monopoly situations. Universal service mandates, fee restrictions, customer service standards, and neutrality requirements can all constrain a private monopolist's worst impulses. But enforcement demands substantial, ongoing government resources, and monopolists are skilled at regulatory capture — turning the agencies meant to constrain them into agencies that protect them from competition.`,

  `The opposing extreme involves the government operating fiber networks directly — building data centers, offering ISP services, and competing with (or replacing) the private sector entirely. Over 750 American towns have taken this approach, operating municipal broadband networks. These communities — mostly conservative, mostly rural, mostly in red states — report the highest customer satisfaction levels of any ISP model. Utah's UTOPIA network is a particularly striking example: a consortium of conservative Utah cities that built a fiber network offering gigabit speeds at prices that make Comcast look like highway robbery.`,

  `The UTOPIA example is instructive precisely because it emerged in one of America's most conservative states. These aren't Sanders-style democratic socialists; they're rock-ribbed Republicans who decided that the free market had failed to deliver adequate broadband and that government could do better. And they were right. UTOPIA consistently ranks among the nation's top-performing networks, with speeds, reliability, and customer satisfaction that private monopolists can't match.`,

  `However, the municipal operation model carries risks that its proponents too often dismiss. Government actors can be unpredictable, sometimes incompetent, occasionally corrupt. Mayors, it turns out, are the weirdest people alive. Consider Sarah Palin, who governed a small Alaskan city before ascending to the vice-presidential nomination. Or Rob Ford, the crack-smoking mayor of Toronto. Or any number of small-town officials who've been caught embezzling funds, granting contracts to cronies, or pursuing personal vendettas through official channels.`,

  `A government-operated ISP run by someone like Palin or Ford could do enormous damage — throttling political opponents' websites, surveilling critics, blocking access to unfavorable news coverage. The First Amendment constrains government action but enforcement is slow and expensive, and the damage done during litigation can be irreversible. Government monopoly ISPs are vulnerable to political capture in ways that private monopolies, for all their faults, are not.`,

  `There is a better approach — one that combines the virtues of public investment with the resilience of competitive markets. It's called essential facilities sharing, and it has a long pedigree in telecommunications law. The idea is straightforward: when a large telecom builds or is granted infrastructure that functions as a natural monopoly, it must rent that infrastructure to competitors at regulated rates. This is how local telephone service worked for decades — AT&T owned the wires, but independent long-distance carriers could rent access to them.`,

  `Applied to fiber, essential facilities sharing means: the government installs fiber conduit and builds data centers, but instead of operating as a monopoly ISP, it opens the infrastructure to multiple competing providers. Any qualified ISP can rent shelf space in government data centers and offer service over the public fiber. Universities, cooperatives, small businesses, nonprofit organizations, even groups of friends with sufficient technical skill — all can become ISPs, offering specialized services tailored to their communities.`,

  `Citizens maintain exit options. If you're dissatisfied with the municipal ISP's service, you can switch to a cooperative, a small business, or a national carrier — all running on the same public fiber. If a mayor goes rogue and starts censoring content through the municipal ISP, citizens can flee to an alternative provider without losing their physical connection. The fiber is a public good; the services running over it are a competitive market.`,

  `This model extends further when governments rent conduit space itself, permitting independent operators to lay separate physical lines for specialized purposes — point-to-point connections for hospitals, dedicated links for academic institutions, private networks for corporate branch offices, low-latency connections for creative industries. The public conduit becomes a platform on which an entire ecosystem of connectivity can flourish.`,

  `This creates what I'd call a truly public internet service — one that combines the operation of a public ISP with infrastructure that enables a diverse marketplace of providers. You don't have to rely on city hall, but you can benefit from it. The government provides quality service for those who want it, while the shared infrastructure ensures that alternatives always exist. Liberation without dependence. Choice without abandonment.`,

  `Now apply this framework to the Eurostack, which focuses on software and services rather than physical infrastructure — though this also requires reconsidering the global fiber system, which is currently structured in ways that enable US government surveillance and give America the ability to disconnect other nations from the internet entirely.`,

  `The EU could procure data centers and services from private contractors, mirroring the commercial ISP model. But EU procurement rules create perverse incentives. The standard model — awarding contracts to the lowest-cost compliant bidder — allows anticompetitive vendors to keep winning contracts by underbidding honest competitors, then making up the difference through lock-in, change orders, and planned obsolescence.`,

  `The Polish train manufacturer Newag provides a cautionary tale. Newag won contracts through competitive bidding, but its trains were rigged with software that immobilized them when they detected maintenance by third-party workshops. The trains would simply refuse to run after independent service — a feature designed to force rail operators to use Newag's expensive maintenance services. Good procurement rules, designed to ensure fair competition, can paradoxically reward vendors who sabotage their own products to extract ongoing revenue.`,

  `Alternatively, the EU could directly operate public data centers, social platforms, mobile operating systems, and applications — the equivalent of a municipal ISP at continental scale. This model works well under competent, rights-respecting governance, but it fails dangerously under authoritarian leadership. Consider Viktor Orbán's Hungary, where government control of media has already created an information desert. Or consider Emmanuel Macron's France, where content moderation decisions have been weaponized against political opponents. Do you really want Nigel Farage moderating your social media?`,

  `EU governments consistently pursue encryption restrictions that would enable security service surveillance of all digital communications, despite rhetorical commitments to privacy — a pattern evident since Edward Snowden's revelations. The UK's Investigatory Powers Act, France's proposed encryption backdoors, the EU's own Chat Control proposal — all represent government attempts to ensure that no digital communication is beyond state reach. A government-operated Eurostack would inherit all of these surveillance ambitions.`,

  `Rather than direct government operation or pure privatization, the EU should develop the Eurostack as a provider of technological public goods — the digital equivalent of essential facilities sharing.`,

  `This means improving federated social platforms like Mastodon and Bluesky through code contributions, server administration tooling, bug bounties, security audits, and moderation assistance. The EU could simplify server creation, enabling communities — churches, unions, neighborhood associations, sports clubs — to operate independent social media instances while maintaining interoperability with the broader network.`,

  `Government-hosted servers should offer public digital homes — free, well-maintained, rights-respecting social media accounts for any EU citizen who wants one. But users dissatisfied with the public system can migrate to cooperative, small business, or corporate alternatives without losing their connections, their followers, their message history, or their data. The exit option is what keeps the public provider honest.`,

  `The EU should expand its Digital Markets Act interoperability mandates, requiring legacy platforms — Facebook, Twitter, TikTok — to provide application programming interfaces that enable departing users to maintain their friendships and conversations across platform boundaries. This would create a kind of Schengen Agreement for social media — free movement of people and their data across digital borders.`,

  `However, effective public internet infrastructure requires service provider liability protections. Imposing legal responsibility for user conduct onto small server operators — making a church's Mastodon administrator legally liable for a parishioner's defamatory post — favors only giant corporations. Only billionaire-backed entities can afford the compliance lawyers, content moderation teams, and legal defense funds needed to operate under strict liability regimes. Liability rules designed to ensure "safety" end up ensuring monopoly.`,

  `The form of government involvement determines whether you get liberation or oppression. A public internet isn't a government-operated internet — it's a system where public investment creates public goods, infrastructure and code and services that enable diverse participation both in consuming and providing digital services. The Eurostack should be Europe's fiber conduit for the digital age: publicly funded, universally accessible, open to all providers, with a public option that serves as both a baseline and a competitive discipline on private alternatives.`,

  `The Eurostack represents a critical response to American technological dominance and an essential project for building independent digital infrastructure. But it must avoid becoming national firewalls 2.0 — fragmented national networks that isolate citizens from the global internet. Instead, it should create a genuinely interoperable public internet, one that is accessible to all users and all providers, that respects human rights by design, and that distributes power rather than concentrating it. The form of government involvement determines everything. Get it right, and you build a public internet that serves the public. Get it wrong, and you build a surveillance apparatus that serves the state.`,
];

export const ARTICLE_TEXT = ARTICLE_PARAGRAPHS.join('\n\n');

export const WORD_COUNT = ARTICLE_TEXT.split(/\s+/).length;
